spring:
  config:
    import: optional:file:.env.test[.properties]

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${DB_URL_META}
    username: ${DB_USER_META}
    password: ${DB_PASSWORD_META}

  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${DB_URL_DATA}
    username: ${DB_USER_DATA}
    password: ${DB_PASSWORD_DATA}

  cloud:
    aws:
      region:
        static: ap-northeast-2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}

  cache:
    type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
